# Generated by Django 3.2.6 on 2022-10-11 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='img_gallary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='recipe_img/')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.recipe')),
            ],
        ),
    ]
