# Generated by Django 3.2.6 on 2022-10-11 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20221012_0021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='img',
            field=models.ImageField(default=False, null=True, upload_to='recipe_img/'),
        ),
    ]
