# Generated by Django 3.2.6 on 2022-10-12 18:02

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_auto_20221012_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingre',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='steps',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
