# Generated by Django 3.2.6 on 2022-10-12 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_auto_20221012_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='img',
            field=models.FileField(upload_to='recipe_img/'),
        ),
    ]
